baseURL = "https://seb.xn--ho-hia.de/"
languageCode = "en"
theme = "metio"
title = "Sebastian Hoß"

pygmentsUseClasses=true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[outputs]
  home = [ "HTML", "RSS", "ATOM", "HUMANS", "FOAF", "SECURITY"]
  section = ["HTML", "RSS", "ATOM"]
  term = ["HTML", "RSS", "ATOM"]
  page = ["HTML", "JSONLD"]

[params]
  mainSections = ["topic"]
  author = "Sebastian Hoß"
  email = "seb@xn--ho-hia.de"
  matrix = "@sebhoss:matrix.org"
  github = "sebhoss"
  mastodon = "https://mastodon.online/@sebhoss"
  work = "seb.xn--ho-hia.de"
  description = "articles about software engineering"
  copyright = "Creative Commons Zero v1.0 Universal"

[permalinks]
  topic = "/topic/:title/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
