baseURL = "https://seb.people.metio.wtf/"
languageCode = "en"
theme = "metio"
title = "Sebastian Hoß"

pygmentsUseClasses=true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[outputs]
  home = [ "HTML", "RSS", "ATOM", "HUMANS", "FOAF"]
  section = ["HTML", "RSS", "ATOM"]
  term = ["HTML", "RSS", "ATOM"]

[params]
  mainSections = ["topic"]
  author = "Sebastian Hoß"
  email = "sebhoss@pm.me"
  matrix = "@sebhoss:matrix.org"
  github = "sebhoss"
  mastodon = "https://mastodon.technology/@sebhoss"
  work = "seb.people.metio.wtf"
  description = "articles about software engineering"

[permalinks]
  topic = "/topic/:title/"
