[mediaTypes]
  [mediaTypes.'application/atom+xml']
    suffixes = ['xml']
  [mediaTypes.'application/rdf+xml']
    suffixes = ['rdf']
  [mediaTypes.'application/ld+json']
    suffixes = ['json']



[outputFormats.Atom]
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.Foaf]
  name = "FOAF"
  mediaType = "application/rdf+xml"
  baseName = "foaf"
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.Humans]
  name = "Humans"
  mediaType = "text/plain"
  baseName = "humans"
  isPlainText = true
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

[outputFormats.JSONLD]
  name = "JSONLD"
  mediaType = "application/ld+json"
  baseName = "jsonld"
  isPlainText = true
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false
