name: Publish Page
on:
  push:
    branches:
      - main
  schedule:
    - cron:  0 2 * * MON
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Hugo: Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - name: Build Website
        run: hugo --minify --printI18nWarnings --printPathWarnings --printUnusedTemplates
      - id: htmltest
        name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: ./htmltest.yml
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: seb.xn--ho-hia.de
      - name: IndexNow
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.indexnow.org/indexnow?url=https://seb.xn--ho-hia.de&key=6da084089795b6f5935480863e2ed4c92d7538f5797f03bf
          method: GET
      - name: Google
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://www.google.com/ping?sitemap=https://seb.xn--ho-hia.de/sitemap.xml
          method: GET
