name: Publish Page
on:
  push:
    branches:
      - main
  schedule:
    - cron:  0 2 * * MON
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Hugo: Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
      - name: Build Website
        run: hugo --minify --printI18nWarnings --printPathWarnings --printUnusedTemplates
      - id: htmltest
        name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: ./htmltest.yml
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: seb.xn--ho-hia.de
